#ifndef AUTO_BRIGHTNESS_PROJECT_AUTO_BRIGHTNESS_H
#define AUTO_BRIGHTNESS_PROJECT_AUTO_BRIGHTNESS_H

#include "bmp_core.h"

#define MAXIMUM_PIXEL_COLOR_VALUE 255.0

BMP_FILE *auto_adjust_image(BMP_FILE *input);


#endif //AUTO_BRIGHTNESS_PROJECT_AUTO_BRIGHTNESS_H
