#ifndef AUTO_BRIGHTNESS_PROJECT_AUTO_BRIGHTNESS_H
#define AUTO_BRIGHTNESS_PROJECT_AUTO_BRIGHTNESS_H

#include "bmp_core.h"

BMP_FILE *auto_adjust_image(BMP_FILE *input);


#endif //AUTO_BRIGHTNESS_PROJECT_AUTO_BRIGHTNESS_H
